version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitonic
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/bitonic
      RUST_LOG: bitonic_service=info,axum=info,tower_http=info
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"