version: '3.1'
services:
  quillpoc:
    depends_on:
      - postgres
    image: dungeoncraw/docker-test:0.1.0-SNAPSHOT
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"