apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-csv-data
  namespace: django-scala-local
  labels:
    app.kubernetes.io/name: django-scala
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
