apiVersion: v1
kind: Service
metadata:
  name: django-scala
  namespace: django-scala-local
  labels:
    app.kubernetes.io/name: django-scala
spec:
  type: NodePort

  selector:
    app.kubernetes.io/name: django-scala

  ports:
    - name: django-http
      protocol: TCP
      port: 80
      targetPort: django-http
      nodePort: 30080

    - name: scala-http
      protocol: TCP
      port: 9000
      targetPort: scala-http
      nodePort: 30090
