[package]
name = "bffadminpatron"
version = "0.1.0"
edition = "2021"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dependencies]
actix-web = "4"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls", "postgres" , "uuid", "chrono"] }
